version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt -t .
      - run:
          name: Run unit tests
          command: |
            python -m pytest